// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXpyrMxN53ToydUKwh807vICr5nnbHnY',
    appId: '1:643833742198:web:2d6a46f142db8d0d0d7057',
    messagingSenderId: '643833742198',
    projectId: 'fir-app-a9803',
    authDomain: 'fir-app-a9803.firebaseapp.com',
    storageBucket: 'fir-app-a9803.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTlob4rPgaRYfQXL30q2GJsYBaTW3Q1w',
    appId: '1:643833742198:android:2413a6bfe99b5f4a0d7057',
    messagingSenderId: '643833742198',
    projectId: 'fir-app-a9803',
    storageBucket: 'fir-app-a9803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl_t5ZdlskTbEg0RKPSjIjYu5DNBLJ4DY',
    appId: '1:643833742198:ios:133d5238b8bc74020d7057',
    messagingSenderId: '643833742198',
    projectId: 'fir-app-a9803',
    storageBucket: 'fir-app-a9803.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl_t5ZdlskTbEg0RKPSjIjYu5DNBLJ4DY',
    appId: '1:643833742198:ios:133d5238b8bc74020d7057',
    messagingSenderId: '643833742198',
    projectId: 'fir-app-a9803',
    storageBucket: 'fir-app-a9803.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsXpyrMxN53ToydUKwh807vICr5nnbHnY',
    appId: '1:643833742198:web:97820c83c129c4620d7057',
    messagingSenderId: '643833742198',
    projectId: 'fir-app-a9803',
    authDomain: 'fir-app-a9803.firebaseapp.com',
    storageBucket: 'fir-app-a9803.appspot.com',
  );
}
